from pathlib import Path


WORKER_ROOT = Path(__file__).resolve().parents[2]

DEFAULT_MODEL_DIR = WORKER_ROOT / "models"
DEFAULT_OUTPUT_DIR = Path("/tmp/gamma-tts-output")
DEFAULT_BROWSER_ONNX_TTS_DIR = DEFAULT_MODEL_DIR / "MOSS-TTS-Nano-100M-ONNX"
DEFAULT_BROWSER_ONNX_CODEC_DIR = DEFAULT_MODEL_DIR / "MOSS-Audio-Tokenizer-Nano-ONNX"
DEFAULT_BROWSER_ONNX_TTS_REPO_ID = "OpenMOSS-Team/MOSS-TTS-Nano-100M-ONNX"
DEFAULT_BROWSER_ONNX_CODEC_REPO_ID = "OpenMOSS-Team/MOSS-Audio-Tokenizer-Nano-ONNX"
