{{- $fullname := include "gamma-operator.fullname" . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gamma-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gamma-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
